#include <exception>

using SocketException = std::runtime_error;